#! /bin/bash
#SBATCH --account=pi-lgagliardi
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=5
#SBATCH --time=10:00:00
#SBATCH --mem=10G
#SBATCH --partition=caslake
#SBATCH --error=methane_err.e
#SBATCH --output=methane.o


cd $SLURM_SUBMIT_DIR
source activate local
#conda activate local
module load python
~/.conda/envs/local/bin/python  /project/lgagliardi/ndohrmann/Desktop/M25510/PySCF_Comp/methane_pyscf.py
